'use strict'
const { shuffleArray } = require('../utils/shuffleArray')

const titles = [
	'Effective Strategies for Improving Reading Comprehension',
	'Navigating Tough Conversations with Parents',
	'Transforming Assessment with Technology',
	'The Power of Play: Integrating Play into Learning',
	'Fostering Creativity in the Classroom',
	'Engaging Students in Critical Thinking and Problem-Solving',
	'Differentiated Instruction for All Learners',
	'Effective Approaches to Distance Learning',
	'Building Positive Teacher-Student Relationships',
	'Mindfulness Practices for Teachers',
	'Strategies for Inclusion in the Classroom',
	'Making the Most of Classroom Technology',
	'Innovative Approaches to Teaching Poetry',
	'Providing Effective Feedback to Students',
	'Empowering Students through Student-Led Conferences',
	'Collaborative Learning in the Classroom',
	'Creating a Safe and Welcoming Classroom Environment',
	'Supporting English Language Learners',
	'Strategies for Classroom Management in Middle School',
	'Making Learning Visible with Visible Thinking Routines',
	'Meeting the Needs of Gifted Students',
	'Promoting Student Agency in the Classroom',
	'Innovative Approaches to Teaching Reading',
	'Effective Approaches to Differentiated Learning',
	'Engaging Students through Project-Based Learning',
	'Strategies for Teaching Vocabulary',
	'Maximizing Student Learning with Effective Feedback',
	'Supporting Students with Mental Health Needs',
	'Using Technology to Promote Learning and Growth',
	'Teaching with Inquiry-Based Learning',
	'Building a Culturally Responsive Classroom',
	'Differentiated Instruction for Students with ADHD',
	'Enhancing Critical Thinking Skills through Classroom Discussions',
	'Strategies for Classroom Management in High School',
	'The Power of Storytelling in Education',
	'Making the Most of Learning Centers in the Classroom',
	'Supporting Students with Special Needs',
	'Strategies for Engaging Students with Attention Deficit Disorder',
	'Effective Strategies for Teaching Grammar',
	'Developing Effective Teacher-Leader Relationships',
	'Innovations in Classroom Assessment and Evaluation',
	'Promoting Social Emotional Learning in the Classroom',
	'Creating a Positive Classroom Climate for All Students',
	'Supporting Students with Learning Disabilities',
	'Making Learning Visible through Student Portfolios',
	'Innovative Approaches to Teaching Science and Technology',
	'Creating Engaging Classroom Activities',
	'Maximizing Learning through Differentiated Instruction',
	'Engaging Students through Multimodal Learning',
	'Strategies for Student-Centered Learning',
	'The Power of Reflection in Learning',
	'Differentiated Instruction for Students with Dyslexia',
	'Building Strong School-Community Relationships',
	'Strategies for Engaging Students with Autism Spectrum Disorder',
	'Effective Approaches to Differentiated Assessment',
	'Enhancing Student Learning through Peer Feedback',
	'Innovative Approaches to Teaching History and Social Studies',
	'Promoting Critical Thinking through Questioning',
	'Teaching Writing through Mentor Texts',
	'Supporting Students with Executive Functioning Challenges',
	'Making the Most of Classroom Libraries',
	'Strategies for Engaging Students in Mathematics',
	'Engaging Students through Technology-Enhanced Learning',
	'Building Strong Teacher Teams',
	'Strategies for Supporting Students with Behavioral Challenges',
	'The Power of Games in the Classroom',
	'Differentiated Instruction for English Language Learners',
	'Maximizing Learning through Collaborative Teaching',
	'Engaging Students through Creative Writing',
	'Strategies for Effective Differentiation',
	'Creating Engaging Learning Activities for Middle School Students',
	'Supporting Students with Emotional and Behavioral Disorders',
	'Differentiated Instruction for Students with Hearing Impairments',
	'Strategies for Engaging Students with Visual Impairments',
	'The Power of Music in the Classroom',
	'Effective Strategies for Classroom Discipline',
	'Innovative Approaches to Teaching Literature',
	'Teaching Strategies for Gifted Students with Learning Disabilities',
	'Creating a Positive Classroom Climate for English Language Learners',
	'Teaching Strategies for Students with Behavioral Disorders',
	'Innovative Approaches to Teaching Foreign Languages',
	'Building a Supportive Classroom Environment for LGBTQ+ Students',
	'Teaching Strategies for Students with Anxiety Disorders',
	'Effective Assessment and Grading Techniques for the Arts',
	'Innovative Approaches to Teaching Philosophy',
	'Teaching Strategies for Students with Trauma',
	'Differentiated Instruction for Students with Attention Deficit Disorders',
	'Creating a Supportive Learning Environment for Gifted and Talented Students',
	'Innovative Approaches to Teaching Media Literacy',
	'Teaching Strategies for Students with Intellectual Disabilities',
	'Effective Classroom Management for Remote Learning',
	'Innovative Approaches to Teaching Life Skills',
	'Teaching Strategies for Students with OCD',
	'Building Positive Classroom Relationships with Students with ADHD',
	'Effective Teaching for Students with Executive Functioning Disorders',
	'Innovative Approaches to Teaching Cultural Competency',
	'Teaching Strategies for Students with Physical Disabilities',
	'Creating a Supportive Learning Environment for Students with Chronic Illnesses',
	'Innovative Approaches to Teaching Human Rights',
	'Teaching Strategies for Students with Developmental Delays',
	'Effective Differentiation for Students with Autism Spectrum Disorders',
	'Innovative Approaches to Teaching Ethics',
	'Teaching Strategies for Students with Learning Challenges',
	'Creating a Supportive Learning Environment for Students with Eating Disorders',
	'Innovative Approaches to Teaching Entrepreneurship',
	'Teaching Strategies for Students with Hearing Loss',
	'Effective Classroom Management for Students with Emotional Disturbances',
	'Innovative Approaches to Teaching Environmental Science',
	'Teaching Strategies for Students with Vision Impairments',
	'Building Positive Classroom Relationships with Students with Social Anxiety',
	'Effective Differentiation for Students with Dyscalculia',
	'Innovative Approaches to Teaching Creative Writing',
	'Teaching Strategies for Students with Speech Disorders',
	'Creating a Supportive Learning Environment for Students with Behavioral Issues',
	'Innovative Approaches to Teaching Technology',
	'Teaching Strategies for Students with Executive Functioning Challenges',
	'Effective Differentiation for Students with Dysgraphia',
	'Innovative Approaches to Teaching Political Science',
	'Teaching Strategies for Students with Dyspraxia',
	'Creating a Supportive Learning Environment for Students with ADHD',
	'Innovative Approaches to Teaching Business',
	'Teaching Strategies for Students with Anxiety and Depression',
	'Effective Classroom Management for Students with Anxiety',
	'Innovative Approaches to Teaching Law',
	'Teaching Strategies for Students with Post-Traumatic Stress Disorder',
	'Creating a Supportive Learning Environment for Students with Dyslexia',
	'Innovative Approaches to Teaching Astronomy',
	'Teaching Strategies for Students with Dyscalculia',
	'Effective Differentiation for Students with Hearing Impairments',
	'Innovative Approaches to Teaching Anthropology',
	'Teaching Strategies for Students with Visual Impairments',
	'Creating a Supportive Learning Environment for Students with Autism Spectrum Disorders',
	'Innovative Approaches to Teaching Geography',
	'Teaching Strategies for Students with Attention Deficit Hyperactivity Disorder',
	'Effective Classroom Management for Students with Autism',
	'Innovative Approaches to Teaching Archaeology',
	'Teaching Strategies for Students with Social Communication Disorders',
	'Creating a Supportive Learning Environment for Students with Intellectual Disabilities',
	'Empowering Students with Self-Directed Learning',
	'The Art of Questioning: Enhancing Classroom Discussions',
	'Differentiated Instruction for Students with Emotional Disturbance',
	'Maximizing Learning through Gamification',
	'Building Strong Parent-Teacher Partnerships',
	'Strategies for Supporting Students with Anxiety in the Classroom',
	'Innovative Approaches to Teaching Coding and Computer Science',
	'Creating Inclusive Classroom Spaces for Students with Disabilities',
	'Differentiated Instruction for Students with Limited English Proficiency',
	'Enhancing Student Learning through Brain-Based Teaching Strategies',
	'The Power of Peer Learning in the Classroom',
	'Supporting Students with ADHD in the Virtual Classroom',
	'Engaging Students through Outdoor Learning',
	'Strategies for Effective Differentiation in Science Education',
	'Building a Trauma-Informed Classroom',
	'Innovative Approaches to Teaching Financial Literacy',
	'Creating a Growth Mindset Culture in the Classroom',
	'Supporting Students with Learning Challenges in the Virtual Classroom',
	'The Art of Reflection: Enhancing Student Learning and Growth',
	'Differentiated Instruction for Students with Giftedness',
	'Maximizing Learning through Differentiated Homework',
	'The Power of Visuals in Learning',
	'Building Resilience in Students through Social Emotional Learning',
	'Innovative Approaches to Teaching Environmental Science',
	'Creating a Classroom Culture of Respect and Kindness',
	'Supporting Students with Autism in the Classroom',
	'Strategies for Enhancing Student Learning through Feedback',
	'Engaging Students through Hands-On Learning',
	'Differentiated Instruction for Students with Language Delays',
	'The Power of Mindful Education',
	'Building a Culturally Responsive Curriculum',
	'Innovative Approaches to Teaching Art',
	'Creating Engaging Classroom Discussions',
	'Supporting Students with Executive Functioning Deficits',
	'Strategies for Effective Differentiation in Physical Education',
	'The Power of Digital Storytelling in Learning',
	'Maximizing Learning through Collaborative Problem-Solving',
	'Differentiated Instruction for Students with Physical Challenges',
	'Engaging Students through Service Learning',
	'Innovative Approaches to Teaching Global Citizenship',
	'Creating Inclusive Learning Spaces for Students with Hearing Impairments',
	'Supporting Students with Depression in the Classroom',
	'Strategies for Effective Differentiation in Social Studies',
	'The Power of Creativity in Learning',
	'Building Strong Teacher-Student Relationships in Middle School',
	'Differentiated Instruction for Students with Chronic Illnesses',
	'Engaging Students through Humor in the Classroom',
	'Innovative Approaches to Teaching Diversity and Inclusion',
	'Creating Engaging Learning Activities for High School Students',
	'Supporting Students with Dyscalculia in the Classroom',
	'Strategies for Effective Differentiation in the Arts',
	'The Power of Imagination in Learning',
	'Building a Positive Classroom Climate for Students with ADHD',
	'Differentiated Instruction for Students with Anxiety Disorders',
	'Engaging Students through Debate and Public Speaking',
	'Innovative Approaches to Teaching Social Justice',
	'Supporting Students with Sensory Processing Disorder',
	'Strategies for Effective Differentiation in Mathematics',
	'The Power of Metacognition in Learning',
	'Building a Culturally Responsive Curriculum for English Language Learners',
	'Differentiated Instruction for Students with Trauma',
	'Engaging Students through Virtual Field Trips',
]

exports.itemTitles = shuffleArray(titles)
